### ISSUE TITLE
Query 06 generates error message for a particular row: WARNINGS: Backend 0:Error converting column: 6 TO DOUBLE (Data is: Nl). 

### ISSUE THREAD

**Issue by nishkamravi2** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#17]

**Comment by Michael-Frank** [comment]
Hi,
could you give details on what system, hadoop stack, execution engine (spark/hive), which versions and scale factors did you encounter this problem?

**Comment by Michael-Frank** [comment]
q6 was updated since this isse started and hive upgrades are available as well. Reopen if this error resourfaces. 
On reopen issuer have to include github version AND hive-version  + basic environment information of his hadoop stack
