### ISSUE TITLE
DataGen/Load issus for large scale factors

### ISSUE THREAD

**Issue by nishkamravi2** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#19]
Encountered problems with data generation/loading for large scale factors (> 4000). In some cases, metastore update gives up for a table.

**Comment by Michael-Frank** [comment]
Hi,
do you think this is a hive bug? How does this problem manifest it self? Does the job terminate or ceases to make any progress?
A log file showing this problem might be helpful.
best regards
Michael

**Comment by nishkamravi2** [comment]
The job terminates if I remember correctly. Don't have the logs anymore (this was from a few days ago). Will have to do a rerun for generating the logs (unfortunately the large cluster is not available at the moment).

**Comment by Michael-Frank** [comment]
not reproducible, not update. Close for now. Reopen if logs are made available.
