### ISSUE TITLE
Big-Bench needs to set query parameters by itself rather than deliver this work to hive.

### ISSUE THREAD

**Issue by LifengWang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#26]
Now Big-Bench will set query parameters through hive shell. It works fine for hive on MapReduce and hive hive on spark.  However it has some issues for other engines. 
- For impala engine, impala shell doesn't support this behavior now. 
- For Spark SQL, it will cost approximately 20 second every query for setting query parameters. For some small queries, the time for setting query parameter cost 1/3 total time.

So it is better that Big-Bench set the query parameters by itself before transferring the hql scripts to the engines.

**Comment by bdgowda1** [comment]
@LifengWang  this is part of localsettings file, closing this for now, re-open if this is still an issue
