### ISSUE TITLE
Query 7 failed due to using left semi join and be referenced in where clause.

### ISSUE THREAD

**Issue by LifengWang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#27]
Query 7 failed and the exception is as follows:
FAILED: SemanticException [Error 10004]: Line 26:26 Invalid table alias or column reference 'q07_cat_avg_price'

Left semi join is used in query 7 and is referenced in where clause. It seems that hive doesn't support this usage. 

"The restrictions of using LEFT SEMI JOIN is that the right-hand-side table should only be referenced in the join condition (ON-clause), but not in WHERE- or SELECT-clauses etc."
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Joins#LanguageManualJoins-JoinSyntax

**Comment by Michael-Frank** [comment]
Hi,
thanks for reporting.Seams we where to eager with trying to be more in line with the original syntax of the corresonding TPC-DS query. I reverted q7 back to a normal join.
best regards
Michael
