### ISSUE TITLE
For table income_band, data generation doesn't generate the Integer data for column ib_lower_bound and ib_upper_bound

### ISSUE THREAD

**Issue by LifengWang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#32]
Now the structure of table income_band is :
ib_income_band_sk   	bigint
ib_lower_bound      	int
ib_upper_bound      int  

While the data for the table generated in HDFS is as follows:
1|10001.0|20000.0
2|20001.0|30000.0
3|30001.0|40000.0
......
The data type of ib_lower_bound and ib_upper_bound is int but the data in HDFS is decimals.

Now the load test works fine on hive because that hive will execute the truncate operations. 
But  on Impala engine, load data from HDFS to hive failed due to the data type conversion issue. 

Error converting column: 1 TO INT (Data is: 10001.0)
Error converting column: 2 TO INT (Data is: 20000.0)
file: hdfs://qac8-node1:8020/user/root/benchmarks/bigbench/data/income_band/income_band_320.dat
record: 
1|10001.0|20000.0

**Comment by Michael-Frank** [comment]
Thanks Lifeng,
i will fix this with the upcoming changes to the dataset.

As a temporary fix, you cloud just change the datatype in your impala create tables script to Decimal.
Dont worry, it wont have any negative effects, as this table is currently not used by any query.

**Comment by Michael-Frank** [comment]
fix is commited. please close if the impala issue is resolved

**Comment by bdgowda1** [comment]
@LifengWang  closing this for now since there is a fix, re-open if this is still an issue
