### ISSUE TITLE
java.io.IOException: Error zipping query logs

### ISSUE THREAD

**Issue by xhao1** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#34]
(1)Description: 
Found on branch 'double-quote-fix' while master may also have similar issue.
Just set scale factor to 1, and run with 'runBenchmark' command to do data generation.
        ----   bin/bigBench runBenchmark -m 40  -f 1 -s 2 -234
Data generation is OK while there exists a small issue -- 'java.io.IOException: Error zipping query logs' reported at the end.

(2)Detail Error Logs in the console:
BigBench preparation: Data generation (this might take a while...)
BigBench preparation: Data generation   finished.       Time(ms):       75554   0h:01m:15s:554ms
BigBench benchmark
BigBench phase 1: Load test skipped due to environment variable SKIP_LOAD_TEST
BigBench phase 2: Power test skipped due to environment variable SKIP_POWER_TEST
BigBench phase 3: Throughput test skipped due to environment variable SKIP_THROUGHPUT_TEST
BigBench benchmark      finished.       Time(ms):       5       0h:00m:00s:005ms
BigBench phase 3: Throughput test skipped due to environment variable SKIP_THROUGHPUT_TEST
BigBench times:
BigBench result: no final score can be computed due to skipping some tests
==============
Benchmark run terminated
Reason: An error occured while running a command
==============
java.io.IOException: Error zipping query logs
        at io.bigdatabenchmark.v1.driver.BigBench.zipQueryLogs(BigBench.java:917)
        at io.bigdatabenchmark.v1.driver.BigBench.run(BigBench.java:359)
        at io.bigdatabenchmark.v1.driver.RunBigBench.main(RunBigBench.java:52)

**Comment by Manuel-Danisch** [comment]
Hi @xhao1,

You will also see this behaviour on the master branch, because you were not actually running any queries. Therefore, you have no query logs, and the zip program returns an error as there are no files present which could be compressed.

Best regards,

Manuel

**Comment by bdgowda1** [comment]
Hi xhao1 - I have marked this issue to be fixed as part of reporting re-organization. If this is a show-stopper please let me know.

**Comment by xhao1** [comment]
Hi, bdgowda1 and  Manuel-Danisch,
It's OK and it's not a show-stopper. We found it during PR30 validation and thought it's a user experience issue which is better to be logged in some place. Thanks.

**Comment by bdgowda1** [comment]
@xhao1  closing this for now, re-open if this is still an issue.
