### ISSUE TITLE
Always 'CLEAN_ALL' the folder named by 'bigbench' regardless of specified folder

### ISSUE THREAD

**Issue by jameszhouyi** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#40]
Hi,
I firstly try to change the default name from 'bigbench' to 'bigbench_new' in conf/userSettings.conf like below: 
export BIG_BENCH_DEFAULT_DATABASE="bigbenchORC_new"
export BIG_BENCH_HDFS_RELATIVE_INIT_DATA_DIR="benchmarks/bigbench_new/data"
export BIG_BENCH_HDFS_RELATIVE_REFRESH_DATA_DIR="benchmarks/bigbench_new/data_refresh"
export BIG_BENCH_HDFS_RELATIVE_QUERY_RESULT_DIR="benchmarks/bigbench_new/queryResults"
export BIG_BENCH_HDFS_RELATIVE_TEMP_DIR="benchmarks/bigbench_new/temp"

And then run "./bin/bigBench runBenchmark -e hive -i CLEAN_ALL  -b" , found currently BB always deletes the 'bigbench' folder(expected to 'bigbench_new' instead of 'bigbench') on HDFS like below a part snippet of logs on console:
cleaning /user/root/benchmarks/bigbench
Deleted /user/root/benchmarks/bigbench
BigBench clean all                                      finished. Time:          0h:00m:12s:265ms

**Comment by Manuel-Danisch** [comment]
Hi @jameszhouyi,

Good catch! Thanks for the report. I fixed it by adding two more variables to userSettings.conf, BIG_BENCH_HDFS_RELATIVE_HOME and BIG_BENCH_HDFS_ABSOLUTE_HOME, which correctly set the directories the way you want it to.

Best regards,

Manuel
