### ISSUE TITLE
Q03 reference result for 1G data size (engines/hive/queries/q03/results) are quite different with current actual result (5 rows VS 100 rows)

### ISSUE THREAD

**Issue by xhao1** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#41]
Q03 reference result for 1G data size (engines/hive/queries/q03/results) are quite different with current actual result.
It has only 5 rows in file engines/hive/queries/q03/results, while the actual hive query result has 100 rows.
Seems that the query has update recently and the reference result file for 1G data size may need to be updated.

(1) engines/hive/queries/q03/results： 5 rows
10000,90,1
10000,2265,1
10000,5595,1
10000,9451,1
10000,16566,1

(2) Actual result:  100 rows

hive> select * from q03_hive_engine_validation_power_test_0_result;
OK
10001   10001   415
10001   9590    215
10001   7612    198
10001   8617    186
10001   5634    184
10001   6623    181
10001   9606    180
...
10001   9702    20
10001   3528    19
10001   2523    18
10001   577     17
10001   1566    17
10001   1774    17
10001   2763    17
Time taken: 0.186 seconds, Fetched: 100 row(s)

**Comment by Michael-Frank** [comment]
updated q3 and validation result set. please retest and close if fixed

**Comment by xhao1** [comment]
Verified based on BB master repo(current latest revision 066d39a9973662156a85e56de868c3c599bd7c4e).
