### ISSUE TITLE
Q30 produced unexpected result with large scale factor

### ISSUE THREAD

**Issue by XiaominZhang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#42]
When scale factor is larger such as 3000 or 10000, the query result of Q30 seems unexpected. For example, below is the result of SF 10000:
1,2,9900000
1,3,9900000
1,4,9900000
1,5,9900000
1,6,9900000
1,7,9900000
1,8,9900000
1,9,9900000
2,3,9900000
2,4,9900000
2,5,9900000
2,6,9900000
2,7,9900000
2,8,9900000
2,9,9900000
3,4,9900000
3,5,9900000
3,6,9900000
3,7,9900000
3,8,9900000
3,9,9900000
4,5,9900000
4,6,9900000
4,7,9900000
4,8,9900000
4,9,9900000
5,6,9900000
5,7,9900000
5,8,9900000
5,9,9900000
6,7,9900000
6,8,9900000
6,9,9900000
7,8,9900000
7,9,9900000
8,9,9900000

It's unreasonable that all category combination has the exact same occurrence. 
This issue seems due to the q30-sessionize.py, as it may produce same "session id" (USERID+SESSION_COUNT) for those sessions which starts from different timestamps.
With below modifications to q30-sessionize.py:

--- a/engines/hive/queries/q30/q30-sessionize.py
+++ b/engines/hive/queries/q30/q30-sessionize.py
@@ -38,9 +38,9 @@ if __name__ == "__main__":
                        # time between clicks exceeds session timeout?
                        if tstamp - last_click_time > timeout:
                                perUser_sessionID_counter += 1
+                               last_click_time=tstamp
                                
-                       last_click_time =tstamp
-                       print "%s\t%s" % (item_sk, user_sk+"_"+str(perUser_sessionID_counter) )
+                       print "%s\t%s" % (item_sk, user_sk+"_"+str(last_click_time)+"_"+str(perUser_sessionID_counter) )
 
It can produce the result as:
2,3,1176152541
2,8,563938823
3,8,521837823
2,5,493365439
3,5,457219891
1,2,368883318
1,3,342223902
2,4,324242034
3,4,300708362
2,9,233459665
5,8,226814295
2,6,222010846
3,9,216632694
2,7,215868309
3,6,206041693
3,7,200347001
1,8,169907963
1,5,149294367
4,8,149282182
4,5,131022992
8,9,107570552
6,8,102330604
7,8,99506154
1,4,98204239
5,9,94449108
5,6,89831892
5,7,87375997
1,9,70776578
1,6,67310695
1,7,65428036
4,9,62149709
4,6,59114712
4,7,57504614
6,9,42607287
7,9,41423476
6,7,39415393

**Comment by bdgowda1** [comment]
@XiaominZhang Is this still an issue?

**Comment by cloudlander** [comment]
It's fixed in recent repo
