### ISSUE TITLE
python scripts throw exceptions on Spark SQL engine

### ISSUE THREAD

**Issue by joshuayao** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#45]
Impact queries with Python scripts. e.g. q30

[Error Log]
Traceback (most recent call last):
  File "q30-sessionize.py", line 29, in <module>
    user_sk, tstamp_str, item_sk  = line.strip().split("\t")
ValueError: need more than 1 value to unpack

[Environment]
Spark 1.5, Hive 0.13.1

We found BB uses '\t' as field separator in python script.  Both Hive and Spark uses '^A' (\001) as the default field separator. Hive switches the separator to '\t' while using transform, but, Spark keeps using the default separator. So, python scripts cannot split each data line successfully on Spark engine. It seems that Spark community has no plan to guarantee the consistency of Hive transform in 1.5 release. So, I suggest to modify BB python script.

e.g. in q30, replace the statement 'user_sk, tstamp_str, item_sk  = line.strip().split("\t")' with the following:
import re
user_sk, tstamp_str, item_sk  = re.split('\t|\001', line.strip())

if it makes sense, I'll submit a PR for the issue.

**Comment by joshuayao** [comment]
Spark community began to fix the issue. Refer to https://issues.apache.org/jira/browse/SPARK-10310

**Comment by bdgowda1** [comment]
@joshuayao can you close this if Spark folks are working on fixing this.
