### ISSUE TITLE
engine specified via '-e' takes no effect when running with runBenchmark command

### ISSUE THREAD

**Issue by XiaominZhang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#51]
When I use below command with spark, the load test is actually performed by the default engine hive:
bin/bigBench runBenchmark -e spark -i ENGINE_VALIDATION_LOAD_TEST
This issue only occurs when running with ENGINE_VALIDATION phases such as LOAD_TEST and POWER_TEST

**Comment by Manuel-Danisch** [comment]
Hi @XiaominZhang,

Yes, the driver ignored that parameter (along with database and map tasks parameters) in the engine validation phase. I added all those missing parameters to the driver. Should be working in 488717d9c23b64c5bedd0d6bed2b47975af7f73b.

Best regards,

Manuel
