### ISSUE TITLE
All ENGINE_VALIDATION phases failed on after rev 488717d

### ISSUE THREAD

**Issue by XiaominZhang** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#52]
It seems the user provided arguments are not corrected handled in the commit 488717d9:
bin/bigBench runBenchmark -b -i ENGINE_VALIDATION_DATA_GENERATION
BigBench benchmark: Start
BigBench engine validation: Data generation             (this might take a while...)
 80 is not a number
Engine directory /data/projects/BB_cloned/engines/ hive not found. Aborting script...
==============
Benchmark run terminated
Reason: An error occured while running a command
==============
java.io.IOException: Error while generating dataset. More information in logfile: /data/projects/BB_cloned/logs/dataGeneration-run_query.log
	at io.bigdatabenchmark.v1.driver.BigBench.generateData(BigBench.java:755)
	at io.bigdatabenchmark.v1.driver.BigBench.run(BigBench.java:393)
	at io.bigdatabenchmark.v1.driver.RunBigBench.main(RunBigBench.java:52)

**Comment by Manuel-Danisch** [comment]
Hi,

issue should be fixed in 4e99dc7f11a2bb9fba963e5285706b5aa10a1a39.

Thanks for the report.

Best regards,

Manuel
