### ISSUE TITLE
Issue with Query2 at 10TB.

### ISSUE THREAD

**Issue by rohit-singhal** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#54]
The way Q2 is written, it grows in a quadratic relationship with the data-size. 
As a result, it is near impossible to successfully run it at large data sets.
For a 9 node cluster that we have set up, the run time for Q2 in the power test is 814 seconds and 3221 seconds at 1TB and 3TB respectively. Clearly this increase in runtime is more than linear. 
For the 10TB data, the query does not complete. A log can be provided if needed (it is omitted because of the size). 

A solution is also attached herein that changes the run complexity to Linear from Quadratic. The only implication of this change on the intermediate output is that the order of the items in a pair is shuffled. The final output after the Mahout stage remains unchanged. 

![q02_change](https://cloud.githubusercontent.com/assets/13595583/10323745/ee483322-6c39-11e5-852c-56764be947ab.jpg)

**Comment by bdgowda1** [comment]
Optimizations included in next release.
