### ISSUE TITLE
Q5 Runtime Improvement

### ISSUE THREAD

**Issue by rohit-singhal** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#56]
The following change results in a 35% runtime improvement for Query 5. The change is to split a massive join into smaller parts that effectively pre-filter data. 
The final output is unchanged. This has been verified at multiple scale factors. 
![q05_change](https://cloud.githubusercontent.com/assets/13595583/10324247/f8009456-6c3c-11e5-87c0-743752a918a1.jpg)

**Comment by bdgowda1** [comment]
optimization included in next release.
