### ISSUE TITLE
Q23 Runtime Improvement

### ISSUE THREAD

**Issue by rohit-singhal** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#57]
The following change results in a 20% runtime improvement for Query 23. 
The final output is unchanged. This has been verified at multiple scale factors.

![q23_change_part1](https://cloud.githubusercontent.com/assets/13595583/10324383/01bec016-6c3e-11e5-869d-8faec3d5f7c2.jpg)
![q23_change_part2](https://cloud.githubusercontent.com/assets/13595583/10324382/01b8a6cc-6c3e-11e5-94c3-dcbd5639a541.jpg)
![q23_change_part3](https://cloud.githubusercontent.com/assets/13595583/10324384/01bf30dc-6c3e-11e5-9902-37c348cb23a5.jpg)
![q23_change_part4](https://cloud.githubusercontent.com/assets/13595583/10324385/01bf303c-6c3e-11e5-9c1f-3feb1bf6359f.jpg)

**Comment by bdgowda1** [comment]
Closing since the changes were withdrawn.
