### ISSUE TITLE
Job stucked

### ISSUE THREAD

**Issue by appkovacs** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#62]
I try to use BigBench for benchmarking on my CDH installation. It is stucked in Data generation state.
State:  ACCEPTED
FinalStatus:    UNDEFINED
Started:    Fri Mar 11 09:12:04 +0100 2016
Elapsed:    1hrs, 3mins, 45sec
Tracking URL:   UNASSIGNED

It is maybe because of overusage of resources. I have already checked and modified yarn.scheduler.maximum-allocation-mb, mapreduce.map.memory.mb, mapreduce.map.java.opts, mapreduce.reduce.memory.mb, mapreduce.reduce.java.opts values.
I have found the rule that:

mapreduce.map.memory.mb < yarn.nodemanager.resource.memory-mb < yarn.scheduler.maximum-allocation-mb

Cluster is running on 2 KVM virtualized VM. Each have 4 CPU cores, first VM have 36 GB RAM and 80 GB disc space, second have 16 GB RAM and 40 GB disc space.

How should values above configured to run jobs on this infrastructure? All the jobs are waiting for execution in ACCEPTED state. I have calculated "optimal" values with tuning spreadsheet, but there are also all the jobs in ACCEPTED state. If one is RUNNING in a short time, it falls back to ACCEPTED again.

**Comment by Michael-Frank** [comment]
Closed - not a BigBench specific problem but general cluster setup issue. 
Please understand that we cannot provide support for cluster setup issues.
You may try the google group: 
[https://groups.google.com/forum/#!forum/big-bench](https://groups.google.com/forum/#!forum/big-bench)

Regarding cluster setup, the following section of our readme might be helpful:
[https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench#cluster-setup](https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench#cluster-setup)
