### ISSUE TITLE
Q15 Validation case is failed

### ISSUE THREAD

**Issue by nakhanha** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#77]
I am seeing following error. Is there something which I am missing ?

Thanks

Validating query : q15
-----------------------------------------------
benchmark phase: engine_validation_power_test
stream number  : 0
user parameter file:
user settings file :
log: /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/logs/q15_hive_engine_validation_power_test_0.log
===============================================
Files /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/q15/results/q15-result and /dev/fd/62 differ
Validation of /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/q15/results/q15-result failed: Query returned incorrect results
Validation failed: Query results are not OK
An error occured while running command:
==========
query_run_validate_method
==========
Please check the log files for details
Command: [bash, /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/bin/bigBench, validateQuery, -q, 15, -p, engine_validation_power_test, -t, 0, -f, 1, -e, hive, -d, bigbench, -m, 4, -U]
got non-zero return value: 1
BigBench engine validation: Check all query results     stream          0, query 15 (15/30) failed. Time:          0h:00m:02s:062ms
BigBench engine validation: Check all query results     failed. Time:          0h:00m:33s:095ms
==============
Benchmark run terminated
Reason: An error occured while running a command in phase ENGINE_VALIDATION_RESULT_VALIDATION
==============
java.io.IOException: Error while running query 15. More information in logfile: /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/logs/q15_hive_engine_validation_power_test_0.log
        at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1492)
        at io.bigdatabenchmark.v1.driver.BigBench$QueryThread.call(BigBench.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by carabolic** [comment]
Hi @nakhanha ,

the results produced by q15 do not match the expected results. Can you please provide me with the output of q15.

In your HDFS there should be a file called `q15_hive_engine_validation_power_test_0_result` under 

```
/user/[BENCHMARK USER]/benchmarks/bigbench/queryResults/
```

**Comment by QiangYouliang** [comment]
> Hi @nakhanha ,
> 
> the results produced by q15 do not match the expected results. Can you please provide me with the output of q15.
> 
> In your HDFS there should be a file called `q15_hive_engine_validation_power_test_0_result` under
> 
> ```
> /user/[BENCHMARK USER]/benchmarks/bigbench/queryResults/
> ```

Hi @carabolic ,
I have the same problem when executing query 20(An error occured while running a command in phase ENGINE_VALIDATION_RESULT_VALIDATION).
The following attachment is the logs of bigbench and hdfs. 
[q20_hive_engine_validation_power_test_0.log](https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench/files/2698776/q20_hive_engine_validation_power_test_0.log)
[q20_hdfs_log.zip](https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench/files/2698781/q20_hdfs_log.zip)
