### ISSUE TITLE
Big-Bench cannot work on Spark yarn-cluster mode

### ISSUE THREAD

**Issue by joshuayao** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#8]
Spark driver cannot get the enviornment parameters specified by Big-Bench if the app master node and Big-Bench are not at the same node.

I think we can translate these environment parameters(${env:xxx}) queries require to hive conf parameters(${hiveconf:xxx}).

**Comment by bdgowda1** [comment]
Hi Joshuayao - current BigBench doesn't support spark, the driver is just a placeholder.

**Comment by joshuayao** [comment]
Hi bdgowda - 30 BigBench queries can work on Spark SQL at standalone, yarn, local mode now after  we worked with Spark community to fix several Spark SQL bugs.
SPARK-5202
SPARK-5237
SPARK-5364

Hope it is helpful.

**Comment by Michael-Frank** [comment]
Hi Joshuayao,
thanks for your great work with the spark community. Do you mind posting the requirements and your steps to sucessfully run bigbench on spark here or on the associated google groups ( https://groups.google.com/forum/#!forum/big-bench ) ?
Helpful things may be the spark settings, hadoop stack in use, required spark version (custom build or the one included in your stack?)...
That would help to push bigbench on spark and be of great value to other people interested in spark.
Maybe we can even include some sort of "bigbench on spark" guide in the Readme of the frontpage.

Do you have any numbers you are allowed to share regarding the performance improvement of Bigbench on hive vs spark?

best regards
Michael

**Comment by joshuayao** [comment]
BB supports Spark local, standalone, yarn-client mode without modifying BB code now. But we cannot enable BB on Spark yarn-cluster mode without changing any code. So, reopen the bug.

**Comment by bdgowda1** [comment]
Josh, can you please provide details on what part of the code needs to be modified.

**Comment by joshuayao** [comment]
BB queries use several environment parameters. e.g. ${env:BIG_BENCH_hive_default_fileformat_result_table} in q01.  For yarn-client mode, it should work because Spark driver works at the same machine with BB. But, for yarn-cluster mode, Spark driver works in application master. If the application master and BB work on different machines, Spark driver will not be able to get environment parameters.  
We also worked around the issue with a tricky approach. We apply all environment parameters as hiveconf to make them be provisioned to other nodes. We tested it with q06. It works, but we didn't test other queries. So, we don't know if there is any other issues of the approach.

**Comment by Manuel-Danisch** [comment]
Hi Joshuayao,
hive does not seem to have this problem. Obviously hive recognizes environment variables and copies them into its hive environment. So at first glance, this seems to be one more spark problem.

If you are able to provide some patches which illustrate your changes, we can discuss if we want to alter the environment variable handling for all queries.

Best regards
Manuel

**Comment by bdgowda1** [comment]
@joshuayao closing this for now, re-open if this is still an issue.
